---
- name: add JRE_HOME to the default environment...
  become: yes
  become_user: root
  with_items:
    - f: oracle-jre.sh
      d: /etc/profile.d
    - f: oracle-jre.env
      d: '{{ java_oracle_jre_home }}'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
